language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_deploy:
- npm run build:prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: master
